# Generated by Django 5.1.4 on 2025-08-06 07:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0015_remove_gmeetschedule_booking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('Connection_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Details', models.TextField(blank=True, null=True)),
                ('Selection_By', models.CharField(choices=[('mentor', 'Mentor chose mentee'), ('mentee', 'Mentee chose mentor'), ('system', 'System assigned')], default='system', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Not Accepted Yet'), ('accepted', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('Interests', models.ManyToManyField(blank=True, to='users.interest')),
                ('Mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_connections', to='users.userdetails')),
                ('Mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_connections', to='users.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='FreeTimeSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.CharField(max_length=20)),
                ('Start_Time', models.TimeField()),
                ('End_Time', models.TimeField()),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='GmeetSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Meeting_Link', models.URLField(blank=True, null=True)),
                ('Meeting_Start_Time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Meeting_End_Time', models.DateTimeField(blank=True, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Active', models.BooleanField(default=True)),
                ('Connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connections.connection')),
            ],
        ),
    ]
