# Generated by Django 5.1.4 on 2025-04-22 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("Booking_ID", models.AutoField(primary_key=True, serialize=False)),
                ("Description", models.TextField(blank=True, null=True)),
                ("Details", models.TextField(blank=True, null=True)),
                (
                    "Mentee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentee_bookings",
                        to="users.userdetails",
                    ),
                ),
                (
                    "Mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentor_bookings",
                        to="users.userdetails",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Educational_levels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Institution_name", models.CharField(max_length=255)),
                ("Education_level", models.CharField(max_length=100)),
                ("Type_Description", models.TextField(blank=True, null=True)),
                ("Created_At", models.DateTimeField(auto_now_add=True)),
                (
                    "User_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.userdetails",
                    ),
                ),
            ],
        ),
    ]
