# Generated by Django 4.2 on 2025-04-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_booking_educational_levels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="Created_At",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="Expertise",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="Field_of_Interest",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="Requirements",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="Years_of_Experience",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="last_login",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="organization_detail",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
