# Generated by Django 4.2 on 2025-04-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_userdetails_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="Proof",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
