# Generated by Django 4.2 on 2025-04-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_userdetails_proof"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="Field_of_Interest",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
