# Generated by Django 5.1.4 on 2025-05-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userdetails_field_of_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='Expertise',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='Phone_Number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
