# Generated by Django 4.2 on 2025-06-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_userdetails_expertise_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetails",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
