# Generated by Django 5.1.4 on 2025-07-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userdetails_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='Selection_By',
            field=models.CharField(choices=[('mentor', 'Mentor chose mentee'), ('mentee', 'Mentee chose mentor'), ('system', 'System assigned')], default='system', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='Interests',
            field=models.ManyToManyField(blank=True, to='users.interest'),
        ),
    ]
