# Generated by Django 5.1.4 on 2025-07-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_interest_booking_selection_by_booking_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Not Accepted Yet'), ('accepted', 'Confirmed')], default='pending', max_length=10),
        ),
    ]
