# Generated by Django 5.1.4 on 2025-07-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Not Accepted Yet'), ('accepted', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
