# Generated by Django 5.1.4 on 2025-07-20 12:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_booking_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmeetSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Meeting_Link', models.URLField(blank=True, null=True)),
                ('Meeting_Start_Time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Meeting_End_Time', models.DateTimeField(blank=True, null=True)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Active', models.BooleanField(default=True)),
                ('Booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.booking')),
            ],
        ),
    ]
