# Generated by Django 5.1.4 on 2025-08-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_freetimeslots'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmeetschedule',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
