# Generated by Django 5.1.4 on 2025-08-06 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_gmeetschedule_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gmeetschedule',
            name='Booking',
        ),
        migrations.RemoveField(
            model_name='freetimeslots',
            name='User',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='GmeetSchedule',
        ),
        migrations.DeleteModel(
            name='FreeTimeSlots',
        ),
    ]
