# Generated by Django 4.2 on 2025-06-24 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_userdetails_is_verified"),
        ("user_auth", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailotp",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="emailotp",
            name="password",
        ),
        migrations.AlterField(
            model_name="emailotp",
            name="email",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_otp",
                to="users.userdetails",
            ),
        ),
    ]
