# Generated by Django 5.1.4 on 2025-04-22 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0002_booking_educational_levels"),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                ("Source_ID", models.AutoField(primary_key=True, serialize=False)),
                ("Source_Name", models.CharField(max_length=255)),
                ("Website_URL", models.URLField(blank=True, max_length=255, null=True)),
                ("Scraper_Order", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Scholarship",
            fields=[
                ("Scholarship_ID", models.AutoField(primary_key=True, serialize=False)),
                ("Scholarship_Name", models.CharField(max_length=255)),
                ("Scholarship_Description", models.TextField(blank=True, null=True)),
                ("Scholarship_Amount", models.IntegerField(blank=True, null=True)),
                ("Start_Date", models.DateTimeField(blank=True, null=True)),
                ("Deadline", models.DateTimeField(blank=True, null=True)),
                ("Eligibility_Criteria", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("Status", models.CharField(blank=True, max_length=50, null=True)),
                ("Created_At", models.DateTimeField(auto_now_add=True)),
                ("Updated_At", models.DateTimeField(auto_now=True)),
                (
                    "Source_ID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scholar.source",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User_Scholarship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Application_Status", models.CharField(max_length=50)),
                ("Applied_Date", models.DateTimeField(auto_now_add=True)),
                ("Review_Date", models.DateTimeField(blank=True, null=True)),
                ("Rejection_Reason", models.TextField(blank=True, null=True)),
                ("is_withdrawn", models.BooleanField(default=False)),
                ("withdrawn_date", models.DateTimeField(blank=True, null=True)),
                ("withdrawal_reason", models.TextField(blank=True, null=True)),
                (
                    "Scholarship_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scholar.scholarship",
                    ),
                ),
                (
                    "User_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.userdetails",
                    ),
                ),
            ],
            options={
                "unique_together": {("User_ID", "Scholarship_ID")},
            },
        ),
    ]
